name: flutter CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: takuyaohashi/setup-flutter@v1
      - uses: subosito/flutter-action@v1.4.0
      - run: flutter pub get
     # - run: flutter test # we have no test yet
      - run: flutter build apk
    #  - run: flutter build ios --release --no-codesign  # runs only on macOS